#!/usr/bin/env python

import argparse
import json
import requests
import sys
import base64
import tempfile
import webbrowser

POST_URL = "https://websh.jiro4989.com/api/shellgei"


def post(code, b64imgs):
    data = json.dumps({"code": code, "images": b64imgs})
    response = requests.post(url=POST_URL, data=data)
    response.raise_for_status()
    result = json.loads(response.text)
    return result


def print_result(result, value):
    if value is None or "":
        return

    print("[ \033[36;1m{0}\033[m ] {1}".format(value, result[value]))


def save_image(b64img):
    img = base64.b64decode(b64img)
    with tempfile.NamedTemporaryFile("wb", delete=False) as t:
        t.write(img)
        return t.name


def encode_image(path):
    with open(file=path, mode="rb") as f:
        data = base64.b64encode(f.read())
        return data.decode(encoding="utf-8")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("code", type=str, help="code to execute on shellgeibot")
    p.add_argument(
        "-v", "--verbose", action="store_true", help="output verbose information"
    )
    p.add_argument(
        "-o",
        "--open",
        action="store_true",
        help="open images with your default browser",
    )
    p.add_argument("-i", "--images", action="append", help="images to upload")
    args = p.parse_args()

    b64imgs = []
    if args.images is not None:
        for path in args.images:
            b64imgs.append(encode_image(path=path))

    result = post(code=args.code, b64imgs=b64imgs)

    if args.verbose:
        for v in ["status", "elapsed_time", "system_message"]:
            print_result(result, v)

        print("[ \033[32;1m{0}\033[m ] {0}".format("stdout"))
        print(result["stdout"], file=sys.stdout)
        print("[ \033[31;1m{0}\033[m ] {0}".format("stderr"), file=sys.stderr)
        print(result["stderr"], file=sys.stderr)
    else:
        print(result["stdout"], file=sys.stdout)
        print(result["stderr"], file=sys.stderr)

    for images in result["images"]:
        filename = save_image(b64img=images["image"])
        if args.open:
            webbrowser.open(url=filename)
