#!/usr/bin/env python

import argparse
import json
import requests
import sys

POST_URL = 'https://websh.jiro4989.com/api/shellgei'


def post(code):
    data = json.dumps({"code": code, "images": []})
    response = requests.post(url=POST_URL, data=data)
    response.raise_for_status()
    result = json.loads(response.text)
    return result


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('code', type=str, help='code to execute on shellgeibot')
    # p.add_argument('-i', '--image', type=str, help='image file path to upload')
    args = p.parse_args()

    result = post(code=args.code)
    print(result['stdout'], file=sys.stdout)
    print(result['stderr'], file=sys.stderr)
